### ISSUE TITLE
how to retrieve a list of all events?

### ISSUE THREAD

**Issue by justoverclockl** [eddiewebb/flarum-calendar#34]
i'm about to write a pr with a widget, but i do not know how fullcalendar works, how can i retrieve a list of last X events?

**Comment by eddiewebb** [comment]
Events follow flarum conventions, you can pull in the frontend store,         `app.store.find('events', {start: info.start.toISOString(), end: info.end.toISOString()})`
https://github.com/eddiewebb/flarum-calendar/blame/379c015491a2a63cdb552509f76499dfc7580a5c/js/src/forum/Components/CalendarPage.js#L111

**Comment by justoverclockl** [comment]
yes i'm do the exact code on your first example, but i get "info is not defined", maybe i need to import something from fullcalendar?
