### ISSUE TITLE
Cannot set content of Item. Key `newDiscussion` is not present.

### ISSUE THREAD

**Issue by cneicy** [eddiewebb/flarum-calendar#55]
When I visit https://xxxxx/events , the event and calendar are not displayed, the following error appears in F12.
```
mount-redraw.js:15 Error: [ItemList] Cannot set content of Item. Key `newDiscussion` is not present.
    at e.setContent (ItemList.ts:147:13)
    at r.sidebarItems (CalendarPage.js:52:15)
    at r.view (CalendarPage.js:29:35)
    at Function.a (render.js:30:16)
    at render.js:155:45
    at render.js:160:3
    at c (render.js:66:8)
    at l (render.js:50:5)
    at f (render.js:374:25)
    at render.js:444:3
```
Here is plugins I installed.
![QQ截图20240521143247](https://github.com/eddiewebb/flarum-calendar/assets/32791896/65cc0e5f-3fad-4cd0-ba70-6785f1eb075a)
FOF Sitemap and Calendar Settings are default.

Flarum in docker
1.8.5
PHP
8.2.18
MySQL
11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Scheduler 
Active
Queue Driver
sync
Session Driver
file
System
alpine

**Comment by cneicy** [comment]
I solved the problem by disabling MSiderbar.But I don't know what the specific reason is.

**Comment by eddiewebb** [comment]
That plug-in is modifying DOM structure it seems outside the standard
method and removing the button expected to be there.

This plug-in could likely add some fault tolerance for non standard
installs.
